### ISSUE TITLE
Screen sharing issue Firefox/Iceweasel

### ISSUE THREAD

**Issue by benoitne** [dani/vroom#111]
Bonjour Daniel, 

Tout d'abord un grand merci super soft !
J'ai un problème concernant le partage d'écran, je n'arrive pas à a faire apparaitre mon écran sur l'ordinateur distant.
J'ai bien tout essayé pour être certain que ca ne vienne pas de ma configuration (c'était le cas au départ sur des paramètres trop restrictifs) j'ai essayé sur appear.in et j'arrive bien a partager l'écran..
Je préfererai utiliser votre soft car il est libre.
N'hésitez pas à me dire s'il y a quelques pré-requis ou ce qui pourrait m'aider à troubleshooter.

Belette

**Comment by dani** [comment]
Bonjour. J'ai effectivement identifié le problème. J'espère pouvoir corriger ça dans la journée. Merci pour la remonté d'info. Ce bug affect d'ailleurs les autres navigateurs, pas seulement Firefox

**Comment by benoitne** [comment]
Super merci ! N'hésitez pas à me dire je peux tester lorsque ca sera résolu

**Comment by benoitne** [comment]
Super tout marche niquel ! Good job ! 
Une petite question, j'aimerais à l'ocasion installer ma propre instance de vroom, j'ai cru comprendre qu'une distribution systemd ferait l'affaire, j'imagine qu'il ne devrait pas trop avoir de difficulté à utiliser ArchLinux ou Parabola ?

**Comment by dani** [comment]
Même systemd n'est pas obligatoire. Mais la seule configuration que je test et pour laquelle je fournit une config c'est CentOS 7. Devrait pas y avoir de problème à l'installer sur autre chose, le plus difficile sera d'installer tous les modules perl nécessaires

**Comment by benoitne** [comment]
Merci pour la réponse.
Pour info, j'ai eu énormement de déconnexions sur une session d'environ une heure (plus d'un 20ènes de déconnexion au niveau du screensharing)
Je vérifiais en // ma connexion Internet qui n'avait pas l'air d'avoir de soucis.
Autre point, j'ai l'impression que si la caméra est en pause et que l'on fait un screensharing il disparait au bout de quelques secondes.
