### ISSUE TITLE
Add an option to limit the number of participants per room

### ISSUE THREAD

**Issue by dani** [dani/vroom#96]
Now that the signaling server is included in VROOM itself, we can do much more stuff with it, including limiting the number of clients allowed to be connected at the same time in a room

**Comment by hsingfoo** [comment]
Daniel,

what is the minimum required bandwith (Audio & Video) per user based on 
the number of users pls?

-HF

**Comment by dani** [comment]
Well, this depends on several factors, including webcam resolutions and frame rate (which defaults to 15fps but is now configurable). But, if you want some approximative numbers

- Between 200 and 300kbps per peer is really the minimum
- Between 300 and 500Kbps per peer is recommended for a good experience
- Audio only will require far less, I guess 100Kbps ~ 150Kbps per peer is enough

(per peer = for each other peer in the room, so total number of peer -1)

In any case, browsers will try adapt to the available bandwidth, each stream will take up to 2Mbps if available.
